1.
Create a new Jupyter notebook and import numpy. 

Load the contents of the second, fourth, and sixth column in Kuperman-BRM-data-2012.csv into a NumPy array, not forgetting to
skip the header (you cannot work with mixed data yet). 

Each row now contains age-of-acquisition data for one English word. 
The first column will be the number of participants with known age of acquisition for the word, 
the second column the average age of acquistion,
and the third column will be a frequency count in the SUBTLEX-US corpus.

In [1]:
import numpy as np

file_path = '/Users/ychen/wise24homework/Kuperman-BRM-data-2012.csv'

# Define the file name
file_name = 'Kuperman-BRM-data-2012.csv'

# read file, choose Column 2, 4, 6, skip the header
data = np.genfromtxt(file_name, delimiter=',', skip_header=1, usecols=(1, 3, 5))

print(data)

[[1.900e+01 1.580e+00 4.120e+02]
 [1.900e+01 1.890e+00 5.289e+03]
 [2.100e+01 2.000e+00 5.000e-01]
 ...
 [2.100e+01       nan 5.000e-01]
 [2.100e+01       nan 5.000e-01]
 [2.100e+01       nan 5.000e-01]]


2.
Normalize the last column in place in order to turn raw frequencies into percentages.

In [2]:
# 归一化最后一列
data[:, -1] = (data[:, -1] / data[:, -1].sum()) * 100

3

In [3]:
# 计算年龄小于等于5的单词数量
words_acquired_in_first_five_years = np.sum(data[:, 1][data[:, 0] <= 5])

4

In [4]:
# 根据习得年龄过滤数组
filtered_data = data[data[:, 0] == 7]

# 计算百分比
percentage_tokens_understood = np.sum(filtered_data[:, -1])

5

In [5]:
# 按最后一列排序，选择最后5000个词，过滤年龄小于等于10的单词
top_5000_words = data[np.argsort(data[:, -1])[-5000:]]
known_words_for_ten_year_old = np.sum(top_5000_words[:, 0][top_5000_words[:, 0] <= 10])

6

In [6]:
# 计算百分比每年的增长
percentage_growth_per_year = np.diff(data[:, -1])

# 找到最大增长的年龄
max_growth_age = np.argmax(percentage_growth_per_year) + 1  # +1 是因为索引从0开始

7

In [8]:
# 计算每年的词汇量增长
vocabulary_growth_per_year = [np.sum(data[:, 0][np.where((data[:, 0] == age) & (data[:, 0] > 1))]) for age in range(1, 18)]

# 找到高峰年龄
peak_growth_age = np.argmax(vocabulary_growth_per_year) + 1

8

In [9]:
# 按最后一列排序，比较原始顺序和排序后的顺序，找到过早学习的单词数量
sorted_indices = np.argsort(data[:, -1])
premature_learning_count = np.sum(sorted_indices != np.arange(len(sorted_indices)))

9

In [10]:
# 计算随机选择相同数量的单词的令牌覆盖率
random_coverage_increase = np.sum(np.random.choice(data[:, 0], size=len(data)) / data[:, -1].sum()) * 100